### ISSUE TITLE
Centre website

### ISSUE THREAD

**Issue by stefanmarjanovic** [yurangaAU/website.yuranga.com#1]
![image](https://user-images.githubusercontent.com/27712605/34086962-2016baa2-e3f4-11e7-9891-d778cbef00d7.png)

1/ centre the page - currently there are many divs which are off centre
2/ make header menu one line (HOME, WEB, CLOUD, TECH, ADMIN, CONTACT)
3/ centre the logo and "home" text 
4/ make website dynamic and full width when zooming out

**Comment by duyngo** [comment]
Migrated to PROD

**Comment by stefanmarjanovic** [comment]
Cool page is centred and full width, looking good. 
But page content is not showing anymore..
![image](https://user-images.githubusercontent.com/27712605/34141671-c7684d92-e4d6-11e7-86ec-e52e443564f6.png)

**Comment by duyngo** [comment]
Migrated to PROD

**Comment by stefanmarjanovic** [comment]
Tested, and works well.
