### ISSUE TITLE
Power builder image not displaying

### ISSUE THREAD

**Issue by stefanmarjanovic** [yurangaAU/website.yuranga.com#2]
Using powerbuilder to implement an image in the body of the homepage, the image is not being displayed 
![image](https://user-images.githubusercontent.com/27712605/34186479-fe08463c-e57f-11e7-8698-8ffdaa42ca86.png)

**Comment by duyngo** [comment]
Migrated to PROD

**Comment by stefanmarjanovic** [comment]
The image should be displayed as full-width 
![image](https://user-images.githubusercontent.com/27712605/34231986-57ef0264-e632-11e7-8fad-9eb9073ea2aa.png)

**Comment by duyngo** [comment]
Migrated to PROD
